spring:          #表示该配置直接为Spring容器负责处理
  rabbitmq:
    host: 127.0.0.1
    virtual-host: vhostname
    port: 5672
    username: admin
    password: admin

    # 开启发送确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true

#    # 消费者ack有3种模式：NONE、AUTO、MANUAL
#    # NONE: 不管消费是否成功mq都会把消息剔除，这是默认配置方式。
#    # MANUAL：手动应答
#    # AUTO：自动应答，除非MessageListener抛出异常。
    listener:
#      direct:
#        acknowledge-mode: MANUAL
      simple:
        acknowledge-mode: manual
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #配置当前要使用的数据源的操作类型那个
    driver-class-name: com.mysql.cj.jdbc.Driver      #配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 1
    filters: stat,wall,log4j     #druid监控配置
    dbcp2:
      min-idle: 5         #数据库连接池的最小维持连接数
      initial-size: 5     #初始化提供的连接数
      max-total: 5          #最大的连接数
      max-wait-millis: 200        #等待连接获取的最大超时时间
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
##          auto: create
#        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true
#    show-sql: true
#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.skonst.report.mapper
# MyBatis
#mybatis-plus:
#  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
#  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
#  mapper-locations: classpath:mapping/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.skonst.report.entity
#  global-config:
#    worker-id: 1 #机器id
#    datacenter-id: 1 #数据标识id
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#    #自定义填充策略接口实现
#    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
#    db-config:
#      db-type: mysql
#      id-type: INPUT  #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#      field-strategy: 2
#      #            logic-delete-value: 1
#      #            logic-not-delete-value: 0
#      table-underline: true
#  configuration:
#    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    #配置JdbcTypeForNull, oracle数据库必须配置
#    jdbc-type-for-null: 'null'
# 日志配置
#logging:
#  level:
#    com.ruoyi: debug
#    org.springframework: warn
#    org.spring.springboot.dao: debug
#  #日志路径，可不写，默认resources下的logback.xml文件
#  config: classpath:logback.xml
